# -*- mode: yaml; -*-
AllCops:
  Exclude:
    - 'templates/**/*'
    - 'spec/**/*'

Style/EmptyLines:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# I dislike this test
Style/StringLiterals:
  Enabled: false


### Metrics
# Rubocop was chosen only for style, and not for complexity or quality checks.
Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
