language: ruby
sudo: false
cache:
  - bundler
  - apt
bundler_args: "--without=release doc"
addons:
  apt:
    packages:
    - build-essential
    - texlive-latex-extra
    - latex-beamer
    - pandoc
    - git-flow git-core
  hosts:
    - travis.dev
before_install:
  - gem install bundler
rvm:
 - 2.0.0
 - 2.1
 - 2.2
 - 2.3
env:
  - TRAVIS_CI_RUN=true GIT_SSH='ssh -o StrictHostKeyChecking=no' GIT_AUTHOR_NAME='Travis CI' GIT_AUTHOR_EMAIL='travis@example.com'
notifications:
  hipchat:
    rooms:
      secure: E0V9xQtCyPSB+SZ5n+ztdM5tzJ7d1eR+XR1gIBfAwe0JYnRb735B1v0Z3CVBmosKpv16KEoKUDjum1vHGk8fnOOcxoHx+TtTCF1TVpuBtKzXqG6t4YZAYjkGSIBUM1Zd7kXLlsdmdwRToGmKRqblQHutnm0LkyII/CAwaO+UeY8=
# addons:
#   code_climate:
#     repo_token:
#       secure: "ZBtaK84ZnjyT4X7mGSYDx31HgD94nZccxAzKA2SBjakW/hfsx9sBGOusxYN7EuC6JydjwLFN3MwLfEGMgjC1zxNwvLO9PGQbh52QawKBue09qouitJbOODwUfQgzNHj/Z0x3dMv3X1Qz31gbfDaC6DJsnTtG2q7R7Kni8hq4/FU="
